/* Sample working documents, explicitly illustrative rather than customer evidence. */
(()=>{
 const section=document.querySelector('.craft-engineer');if(!section)return;
 const tabs=[...section.querySelectorAll('[data-craft]')],paper=section.querySelector('#craft-paper');
 const pages=[
  {title:'A voice worth recognising.',type:'Voice study',description:'Learns your tone and vocabulary.',body:`<blockquote>“The best ideas aren’t in the content calendar. They’re in the conversations <mark>your team is already having.</mark>”</blockquote><div class="craft-notes"><p><b>Vocabulary</b>Concrete. Familiar. Your own.</p><p><b>Point of view</b>Experience before advice.</p></div><p class="craft-pencil">Keep the way you actually say it.</p>`},
  {title:'Know who needs to hear it.',type:'Audience brief',description:'Maps your ideal audience.',body:`<div class="craft-brief"><p><b>Who</b>Leadership teams building a company-wide presence.</p><p><b>The question</b>“How do we turn our expertise into a reason to choose us?”</p><p><b>What they need to see</b>A clear point of view. Evidence. People who know the work.</p></div><p class="craft-pencil">Write for a decision, not a demographic.</p>`},
  {title:'The idea, in your words.',type:'Working draft',description:'Generates voice-matched drafts for your Content Engineer to edit.',body:`<div class="craft-draft"><p><del>In today’s fast-paced world, thought leadership is more important than ever.</del></p><p class="craft-replacement">Your company’s best ideas rarely make it out of the meeting.</p><p>That’s where we start.</p><p>The conversation. The hard-won lesson. The opinion someone almost kept to themselves.</p></div><p class="craft-pencil">Lead with something you believe.</p>`},
  {title:'An idea with a visual life.',type:'Design study',description:'Designs carousels and infographics in your brand.',body:`<div class="craft-design"><div class="craft-cover"><span>Draper</span><strong>The ideas<br>inside<br><em>the room.</em></strong><span>Bring them into the world. ↗</span></div><div class="craft-design-note"><span class="craft-swatch"></span><span>Paper.<br>Ink.<br>A point of view.</span></div></div>`},
  {title:'Keep the part that matters.',type:'Edit decision',description:'Cuts talking-head film with captions and motion.',body:`<div class="craft-edit"><p class="craft-transcript"><span>“So, um, I think what I was trying to say is…”</span><strong>“The real lesson was knowing what to leave out.”</strong></p><div class="craft-strip" aria-label="Opening, insight and close"><span>Opening</span><b>The insight</b><span>Close</span></div><p class="craft-edit-note">Cut the preamble.<br>Give the insight room to land.</p></div>`},
  {title:'Learn from the work.',type:'Editorial review',description:'Monitors engagement signals to inform the next editorial decision.',body:`<div class="craft-review"><p><b>Keep</b><span>The ideas that start relevant conversations.</span></p><p><b>Rework</b><span>Strong thinking that needs a clearer opening.</span></p><p><b>Test</b><span>A new angle on a subject your audience cares about.</span></p></div><p class="craft-pencil">The next piece should know more.</p>`},
  {title:'Notice who leans in.',type:'Conversation brief',description:'Flags relevant interactions from your ideal audience.',body:`<div class="craft-conversation"><div><span class="craft-person" aria-hidden="true"></span><p>A relevant voice<br><small>In your target audience</small></p></div><blockquote>“How are you approaching this with your team?”</blockquote><p class="craft-response">A question worth a human reply.</p></div><p class="craft-pencil">Attention becomes a conversation.</p>`}
 ];
 let active=0;
 function show(i,focus=false){active=i;const page=pages[i];tabs.forEach((t,n)=>{t.setAttribute('aria-selected',String(n===i));t.tabIndex=n===i?0:-1});section.querySelector('#craft-output').setAttribute('aria-labelledby',tabs[i].id);paper.innerHTML=`<div class="craft-dochead"><span>${page.type}</span><span aria-hidden="true">D.</span></div><h3>${page.title}</h3>${page.body}`;section.querySelector('#craft-description').textContent=page.description;if(focus)tabs[i].focus();if(document.documentElement.dataset.motion!=='paused'&&!matchMedia('(prefers-reduced-motion: reduce)').matches)paper.animate([{opacity:.35,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:260,easing:'cubic-bezier(.22,1,.36,1)'});}
 tabs.forEach((t,i)=>{t.addEventListener('click',()=>show(i));t.addEventListener('keydown',e=>{let next;if(['ArrowRight','ArrowDown'].includes(e.key))next=(active+1)%tabs.length;if(['ArrowLeft','ArrowUp'].includes(e.key))next=(active+tabs.length-1)%tabs.length;if(e.key==='Home')next=0;if(e.key==='End')next=tabs.length-1;if(next!==undefined){e.preventDefault();show(next,true)}})});show(0);
 const mq=matchMedia('(max-width:760px)');const orient=()=>{section.querySelector('[role=tablist]').setAttribute('aria-orientation',mq.matches?'horizontal':'vertical');section.querySelector('.craft-prompt>span').textContent=mq.matches?'→':'↓'};mq.addEventListener('change',orient);orient();
})();
